POST http://127.0.0.1:3000/api/auth/registro
Content-Type: application/json

{
    "nombre": "Juan",
    "apellidos": "Medina",
    "email": "juan@email.com",
    "password": "juan123456"
}

### LOGIN
POST http://127.0.0.1:3000/api/auth/login
Content-Type: application/json

{
    "email": "juan@email.com",
    "password": "juan123456"
}


### PERFIL
GET http://127.0.0.1:3000/api/auth/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb3JyZW8iOiJqdWFuQGVtYWlsLmNvbSIsImlkIjo0LCJ0aW1lIjoiMjAyMy0wNC0xNFQwMDoxNzoxNi43MTJaIiwidGllbXBvX2V4cGlyYWNpb24iOiIxaCIsImlhdCI6MTY4MTQzMTQzNiwiZXhwIjoxNjgxNDM1MDM2fQ.ksiLGc09Hv9xv_M41nHEGhR6Cw8AQhwlHvBn8W30pf4