POST http://127.0.0.1:3000/api/auth/registro
Content-Type: application/json

{
    "nombre": "Juan",
    "apellidos": "Medina",
    "email": "juan@email.com",
    "password": "juan123456"
}

### LOGIN
POST http://127.0.0.1:3000/api/auth/login
Content-Type: application/json

{
    "email": "santy@mail.com",
    "password": "12345"
}


### PERFIL
GET http://127.0.0.1:3000/api/auth/perfil